### ISSUE TITLE
field_domain_access should not be required if field_domain_all_affiliates is checked

### ISSUE THREAD

**Issue by nedjo** [agentrickard/domain#251]
Related: #250 

When editing a node with domain_access installed, if ```field_domain_all_affiliates``` is checked, ```field_domain_access``` is redundant and so should not be required.

**Comment by agentrickard** [comment]
From a storage perspective, this is not true. 'All affiliates" visibility is different from editorial assignments. Since people can edit content assigned to their domains, we have valid cases where content may be published to All Affiliates, but only editable by people in Domain A.

This has always been the case.
