### ISSUE TITLE
Backend editing on multiple Instances (local/stage/prod)

### ISSUE THREAD

**Issue by pheadeaux** [agentrickard/domain#287]
As admin, when working on an other environment than production, "editing content" will always send me to the production domain.

I'm using a acquia hosting setup. There is a dev environment, stage environment, prod environment, and a local development environment (each configered with different domains). When logged in on `http://stage.domain.com/admin/content/` every link to `/node/id/edit` will be replaced with `https://prod.domain.com/node/id/edit` when a domain source is set to this very node.

`http://stage.domain.com` is a proper domain alias to the default domain.

To actually edit the node I have to copy the link and rewrite the `prod` to `stage` in this case.

I followed the link creation to `lib/Drupal/Core/Routing/UrlGenerator.php:320` `$options['base_url']`. But there is noting wrong there, I guess.

So is this a misconfiguration in my setup? or a intended design?

I searched the github issues, the drupal issues and (old) install instructions.

Great module, thanks for the effort!

**Comment by agentrickard** [comment]
This is probably a missing piece in Domain Source -- which is still alpha and hasn't really been given much testing.

It means that DomainSourcePathProcessor::processOutbound() needs to be sensitive to the alias status.

**Comment by agentrickard** [comment]
On review, this is a bit of a complex problem, because in this case, you probably want the entire set of domain references changes to match the alias pattern of the test environment.

Here's how we handled that in Drupal 7:

https://www.drupal.org/node/1096988 (See the section on Managing Site Development.)

I had an approach that worked in D7 worked into code as well: https://www.drupal.org/node/1303616

I think this is something that needs to be handled in a custom module at the moment, but looking through the core code, I don't know that there is an entity_load_alter() anymore.

There is, however, hook_domain_source_alter() which you can leverage in a custom module to enforce the behavior you want. However, because the results of that function call Domain::getPath(), I don't think you can alter that result directly.

I think in an ideal world, we might ass a config setting in settings.php that indicates the Alias set to use, and then we can store the set as part of the Alias.

I am open to ideas, but here's a function to get you started.

```
function domain_alias_domain_source_alter($source, $path, $options) {
  $active = \Drupal::service('domain.negotiator')->getActiveDomain();
  if ($active->id() == $source->id() && $active->getMatchType() == DomainNegotiator::DOMAIN_MATCH_ALIAS) {
    $hostname = $active->get('alias');
    if ($hostname && !$active->getRedirect()) {
      $source->setHostname($hostname);
      $source->setPath();
    }
  }
}
```

**Comment by pheadeaux** [comment]
Well, I was quite unsure how to approach this. Because I am still quite unsure how to use this module on a local basis. Leave aside my initial setup. How would you even set up two environments: local Development and Production? Maintaining this would be impossible, since you could not edit (without much hassle) your local content. You would be sent to the prod environment.

In my ideal scenario, the CRUD function in the backend would just use relative paths. Leaving out the domain part of the url. So even working on your localhost would be possible.
But since I stepped through the core `UrlGenerator.php:320`, the urls have to have an absolute url, I guess.

So `Domain Source` would need to know from the current request, which alias or domain record is set and rewrite the Urls. Leaving aside local development.

Thanks for the code, I will try to implement something like that.

**Comment by zerolab** [comment]
OTOH, you could shortcut this by overriding the hostname in your local settings file.

```php
// Stage.
$config['domain.record.main_domain_machine_name']['hostname'] = 'stage.domain.com';
$config['domain.record.secondary_domain']['hostname'] = 'stage2.domain.com';

// Dev.
$config['domain.record.main_domain_machine_name']['hostname'] = 'domain.dev';
```

I'd recommend a code based approach, though.

**Comment by agentrickard** [comment]
I don't know. I think the settings.local.php approach might actually be safer. 

I had forgotten that you can do that with config entities.

We could possibly override that in a Domain Alias event subscriber, I think. What we might do is:

* Allows each alias to belong to a "set" or "group"
* On negotiation, read the active set from the alias match (if present)
* Alter the entities based on matching alias sets.

In that way, you might have a set of "dev" aliases that all load in sync.

The problem with that approach is wildcards in aliases. For those to work, all members of a set would have to have the same wildcard pattern (e.g. *.example.dev, *.example.test, *.example.com could be a set, where the * is dynamically replaced by the request).

**Comment by agentrickard** [comment]
You can also disable Domain Source on local. That would work, too.

**Comment by agentrickard** [comment]
I've spun up the 287-alias branch to work on this.
